spring.application.name=SpringBootMvc07MiniProject-CURDoperations
#view Resolver cfg
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp
#Embeded server port number
server.port=8689
#Contextpath
server.servlet.context-path=/Employee-CURDOperations
#DataSource config
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=c##demo
spring.datasource.password=lion
#Hibernate JPA_properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.Oracle10gDialect